# Generated by Django 4.1.4 on 2023-01-18 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotiser',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
