# Generated by Django 4.1.4 on 2023-01-19 04:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0002_alter_cotiser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='interet',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='pret',
            name='sanction',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Rembourserpret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('date_remboursement', models.DateField(default=datetime.date.today)),
                ('id_membre', models.ForeignKey(db_column='id_membre', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_pret', models.ForeignKey(db_column='id_pret', on_delete=django.db.models.deletion.CASCADE, to='tontine.pret')),
            ],
            options={
                'db_table': 'Rembourser_pret',
            },
        ),
    ]
