# Generated by Django 4.1.4 on 2023-01-19 09:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0003_alter_pret_interet_alter_pret_sanction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuerfond',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pret',
            name='interet',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='beneficiare',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='ListePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_membre', models.ForeignKey(db_column='id_membre', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_reunion', models.ForeignKey(db_column='id_reunion', on_delete=django.db.models.deletion.CASCADE, to='tontine.reunion')),
            ],
            options={
                'db_table': 'Liste_Presence',
            },
        ),
    ]
